/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tmarketplace_constants.h"

namespace OpenStars { namespace Platform { namespace MarketPlace {

const tmarketplaceConstants g_tmarketplace_constants;

tmarketplaceConstants::tmarketplaceConstants() {
}

}}} // namespace

