/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TMediaStorageService_H
#define TMediaStorageService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "tmediastorage_types.h"
#include "TDataService.h"

namespace OpenStars { namespace Common { namespace TMediaStorageService {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TMediaStorageServiceIf : virtual public TDataServiceIf {
 public:
  virtual ~TMediaStorageServiceIf() {}
};

class TMediaStorageServiceIfFactory : virtual public TDataServiceIfFactory {
 public:
  typedef TMediaStorageServiceIf Handler;

  virtual ~TMediaStorageServiceIfFactory() {}

  virtual TMediaStorageServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TDataServiceIf* /* handler */) = 0;
};

class TMediaStorageServiceIfSingletonFactory : virtual public TMediaStorageServiceIfFactory {
 public:
  TMediaStorageServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<TMediaStorageServiceIf>& iface) : iface_(iface) {}
  virtual ~TMediaStorageServiceIfSingletonFactory() {}

  virtual TMediaStorageServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TDataServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<TMediaStorageServiceIf> iface_;
};

class TMediaStorageServiceNull : virtual public TMediaStorageServiceIf , virtual public TDataServiceNull {
 public:
  virtual ~TMediaStorageServiceNull() {}
};

class TMediaStorageServiceClient : virtual public TMediaStorageServiceIf, public TDataServiceClient {
 public:
  TMediaStorageServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    TDataServiceClient(prot, prot) {}
  TMediaStorageServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :    TDataServiceClient(iprot, oprot) {}
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
};

class TMediaStorageServiceProcessor : public TDataServiceProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<TMediaStorageServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TMediaStorageServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
 public:
  TMediaStorageServiceProcessor(::apache::thrift::stdcxx::shared_ptr<TMediaStorageServiceIf> iface) :
    TDataServiceProcessor(iface),
    iface_(iface) {
  }

  virtual ~TMediaStorageServiceProcessor() {}
};

class TMediaStorageServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TMediaStorageServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< TMediaStorageServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< TMediaStorageServiceIfFactory > handlerFactory_;
};

class TMediaStorageServiceMultiface : virtual public TMediaStorageServiceIf, public TDataServiceMultiface {
 public:
  TMediaStorageServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<TMediaStorageServiceIf> >& ifaces) : ifaces_(ifaces) {
    std::vector<apache::thrift::stdcxx::shared_ptr<TMediaStorageServiceIf> >::iterator iter;
    for (iter = ifaces.begin(); iter != ifaces.end(); ++iter) {
      TDataServiceMultiface::add(*iter);
    }
  }
  virtual ~TMediaStorageServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<TMediaStorageServiceIf> > ifaces_;
  TMediaStorageServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<TMediaStorageServiceIf> iface) {
    TDataServiceMultiface::add(iface);
    ifaces_.push_back(iface);
  }
 public:
};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TMediaStorageServiceConcurrentClient : virtual public TMediaStorageServiceIf, public TDataServiceConcurrentClient {
 public:
  TMediaStorageServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    TDataServiceConcurrentClient(prot, prot) {}
  TMediaStorageServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :    TDataServiceConcurrentClient(iprot, oprot) {}
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}}} // namespace

#endif
