/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tcommentstorage_CONSTANTS_H
#define tcommentstorage_CONSTANTS_H

#include "tcommentstorage_types.h"

namespace OpenStars { namespace Common { namespace TCommentStorageService {

class tcommentstorageConstants {
 public:
  tcommentstorageConstants();

};

extern const tcommentstorageConstants g_tcommentstorage_constants;

}}} // namespace

#endif
