/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tcommentstorage_constants.h"

namespace OpenStars { namespace Common { namespace TCommentStorageService {

const tcommentstorageConstants g_tcommentstorage_constants;

tcommentstorageConstants::tcommentstorageConstants() {
}

}}} // namespace

