/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef StringMapKVService_H
#define StringMapKVService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "stringmapkv_types.h"
#include "TDataService.h"

namespace OpenStars { namespace Common { namespace StringMapKV {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class StringMapKVServiceIf : virtual public TDataServiceIf {
 public:
  virtual ~StringMapKVServiceIf() {}
};

class StringMapKVServiceIfFactory : virtual public TDataServiceIfFactory {
 public:
  typedef StringMapKVServiceIf Handler;

  virtual ~StringMapKVServiceIfFactory() {}

  virtual StringMapKVServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TDataServiceIf* /* handler */) = 0;
};

class StringMapKVServiceIfSingletonFactory : virtual public StringMapKVServiceIfFactory {
 public:
  StringMapKVServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<StringMapKVServiceIf>& iface) : iface_(iface) {}
  virtual ~StringMapKVServiceIfSingletonFactory() {}

  virtual StringMapKVServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TDataServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<StringMapKVServiceIf> iface_;
};

class StringMapKVServiceNull : virtual public StringMapKVServiceIf , virtual public TDataServiceNull {
 public:
  virtual ~StringMapKVServiceNull() {}
};

class StringMapKVServiceClient : virtual public StringMapKVServiceIf, public TDataServiceClient {
 public:
  StringMapKVServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    TDataServiceClient(prot, prot) {}
  StringMapKVServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :    TDataServiceClient(iprot, oprot) {}
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
};

class StringMapKVServiceProcessor : public TDataServiceProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<StringMapKVServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (StringMapKVServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
 public:
  StringMapKVServiceProcessor(::apache::thrift::stdcxx::shared_ptr<StringMapKVServiceIf> iface) :
    TDataServiceProcessor(iface),
    iface_(iface) {
  }

  virtual ~StringMapKVServiceProcessor() {}
};

class StringMapKVServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  StringMapKVServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< StringMapKVServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< StringMapKVServiceIfFactory > handlerFactory_;
};

class StringMapKVServiceMultiface : virtual public StringMapKVServiceIf, public TDataServiceMultiface {
 public:
  StringMapKVServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<StringMapKVServiceIf> >& ifaces) : ifaces_(ifaces) {
    std::vector<apache::thrift::stdcxx::shared_ptr<StringMapKVServiceIf> >::iterator iter;
    for (iter = ifaces.begin(); iter != ifaces.end(); ++iter) {
      TDataServiceMultiface::add(*iter);
    }
  }
  virtual ~StringMapKVServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<StringMapKVServiceIf> > ifaces_;
  StringMapKVServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<StringMapKVServiceIf> iface) {
    TDataServiceMultiface::add(iface);
    ifaces_.push_back(iface);
  }
 public:
};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class StringMapKVServiceConcurrentClient : virtual public StringMapKVServiceIf, public TDataServiceConcurrentClient {
 public:
  StringMapKVServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    TDataServiceConcurrentClient(prot, prot) {}
  StringMapKVServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :    TDataServiceConcurrentClient(iprot, oprot) {}
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}}} // namespace

#endif
