/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tnotifystorage_CONSTANTS_H
#define tnotifystorage_CONSTANTS_H

#include "tnotifystorage_types.h"

namespace OpenStars { namespace Common { namespace TNotifyStorageService {

class tnotifystorageConstants {
 public:
  tnotifystorageConstants();

};

extern const tnotifystorageConstants g_tnotifystorage_constants;

}}} // namespace

#endif
